//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterClone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSON()
        {
            this.FOLLOWINGs = new HashSet<FOLLOWING>();
            this.TWEETs = new HashSet<TWEET>();
        }
    
        public string user_id { get; set; }
        public string password { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public System.DateTime joined { get; set; }
        public bool active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOLLOWING> FOLLOWINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TWEET> TWEETs { get; set; }
        public FOLLOWING followdata { get; set; }
        public TWEET TweetData { get; set; }

        public List<PERSON> peopleData { get; set; }
    }
}
